name: Image Build
description: Build, Push and Scan an image
inputs:
  name:
    required: true
    description: "Name of image"
  context:
    required: true
    description: "Context path"
runs:
  using: "composite"
  steps:
    - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      env:
        IMAGE_NAME: ${{env.REGISTRY}}/${{env.IMAGE_PREFIX}}${{inputs.name}}
      with:
        context: ${{inputs.context}}
        push: true
        tags: ${{env.IMAGE_NAME}}:${{env.VERSION}}.${{env.BUILD_NUMBER}} , ${{env.IMAGE_NAME}}:${{env.VERSION}} , ${{env.IMAGE_NAME}}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      with:
        image: ${{env.REGISTRY}}/${{env.IMAGE_PREFIX}}${{inputs.name}}
        args: --file=${{inputs.context}}/Dockerfile
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
