apiVersion: v1
kind: Namespace
metadata:
  name: simple-example-build-env
---
apiVersion: v1
kind: Namespace
metadata:
  name: simple-example-runtime-env
---
apiVersion: jabos.io/v1
kind: GitRepository
metadata:
  name: first-repo
  namespace: simple-example-build-env
spec:
  url: https://github.com/srfrnk/jabos.git
  runtimeNamespace: simple-example-runtime-env
  branch: main
---
apiVersion: jabos.io/v1
kind: DockerImage
metadata:
  name: first-image
  namespace: simple-example-build-env
spec:
  gitRepository: first-repo
  contextPath: operator
  imageName: registry.kube-system:80/example-image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
        - name: test-deployment
          image: registry.kube-system:80/example-image:fee06a712f1ed7b2f36381213b9ba3f30ba80b0c
