name: Image Build
description: Build, Push and Scan an image
inputs:
  name:
    required: true
    description: "Name of image"
  context:
    required: true
    description: "Context path"
  build-args:
    required: false
    description: "Optional build args to use"
    default: ""
runs:
  using: "composite"
  steps:
    - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      env:
        IMAGE_NAME: ${{env.REGISTRY}}/${{env.IMAGE_PREFIX}}${{inputs.name}}
      with:
        build-args: |
          IMAGE_PREFIX=${{env.REGISTRY}}/${{env.IMAGE_PREFIX}}
          IMAGE_VERSION=:${{env.VERSION}}.${{env.BUILD_NUMBER}}
        context: ${{inputs.context}}
        push: true
        tags: ${{env.IMAGE_NAME}}:${{env.VERSION}}.${{env.BUILD_NUMBER}} , ${{env.IMAGE_NAME}}:${{env.VERSION}} , ${{env.IMAGE_NAME}}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - run: snyk test --sarif-file-output=snyk.sarif --file="${{inputs.context}}/Dockerfile" --docker "${{env.REGISTRY}}/${{env.IMAGE_PREFIX}}${{inputs.name}}" || true
      shell: bash
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
        category: ${{inputs.name}}
