apiVersion: v1
kind: Config
current-context: kubernetes
clusters:
  - name: kubernetes
    cluster:
      certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      server: https://kubernetes.default.svc
contexts:
  - name: kubernetes
    context:
      cluster: kubernetes
